apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    component: {{ .Values.component }}
    vendor: forgerock
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.component }}
        vendor: forgerock
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      initContainers:
      - name: git-init
        image: forgerock/git:6.0.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name:  {{ template "fullname" . }}
        env:
        # This is here so that a change in the git branch or commit triggers a rollout.
        # See https://github.com/kubernetes/helm/issues/2639
        - name: GIT_CHECKOUT_BRANCH
          value: "{{ default "master" .Values.global.git.branch }}"
      containers:
      - name: openidm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /openidm/info/ping
            port: {{ .Values.service.internalPort }}
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value:  "true"
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: openidm-secrets
          mountPath: /opt/openidm/secrets
        - name: logs
          mountPath: /opt/openidm/logs
        - name: git
          mountPath: /git
        - name: boot-properties
          mountPath: /var/run/openidm/commons
        - name: logging-properties
          mountPath: /var/run/openidm/logging
      - name: git
        image: forgerock/git:6.0.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: COMPONENT
          value:  {{ .Values.component }}
        args: [ "{{.Values.git.command}}" ]
      - name: proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances={{ .Values.connectionName }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      {{ if .Values.debug }}
      # sidecar with psqsl client for debugging the database.
      - name: psql
        image: postgres:9.6.3
        args: ["sh", "-c", "sleep 1000000"]
      {{ end }}
      volumes:
      - name: openidm-secrets
        secret:
          secretName: openidm-secrets
      - name: logs
        emptyDir: {}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName:  git-ssh-key
          # This gets mounted as root, so we need to open up the permissions for the forgerock user to read it
          # defaultMode: 256
      - name: boot-properties
        configMap:
          name: idm-boot-properties
      - name: logging-properties
        configMap:
          name: idm-logging-properties
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
