# This is a dummy secret to keep the git init containers happy. They want to mount
# this secret - even though ssh is not required to pull from the public forgeops-init repository.
apiVersion: v1
kind: Secret
data:
  id_rsa: thisisadummykeyvalue
metadata:
  name: git-ssh-key
