apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.djInstance }}
data:
  BASE_DN: {{ .Values.baseDN }}
  # example: configstore, cts, userstore. The instance is used to construct the FQDN of DJ.
  DJ_INSTANCE: {{ .Values.djInstance }}
  DS_SET_SIZE: "{{ .Values.replicas }}"
  OPENDJ_JAVA_ARGS: {{ .Values.opendjJavaArgs }}
  BACKUP_SCHEDULE_FULL: {{ .Values.backupScheduleFull }}
  BACKUP_SCHEDULE_INCREMENTAL: {{ .Values.backupScheduleIncremental }}
  BOOTSTRAP:  {{ .Values.bootstrapScript }}
  BOOTSTRAP_TYPE: {{ .Values.bootstrapType }}
  SLACK_URL: {{ .Values.slackUrl }}
{{- if not (empty .Values.numberSampleUsers) }}
  NUMBER_SAMPLE_USERS: "{{ .Values.numberSampleUsers }}"
{{- end }}
