{{ if gt ( int .Values.replicas ) 1 }}
# This is an optional job that configures replication and schedules backups.
# We run this if the number of replicas is > 1
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.djInstance }}-replication-setup
  labels:
    djInstance: {{ .Values.djInstance }}
    app: {{ template "fullname" . }}
    vendor: forgerock
    component: opendj
spec:
  template:
    spec:
      containers:
      - name: opendj
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.djInstance }}
        args: ["run-post-setup-job"]
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
      restartPolicy: Never
    #backoffLimit: 4
      volumes:
      - name: dj-secrets
        secret:
          secretName: {{ .Values.djInstance }}
          # If we are running as non root, we can't set this mode to root read only
          #defaultMode: 256
{{end}}
